name: fullstack-prac-backend

services:
    db:
        container_name: db-container
        image: postgres

        environment:
            POSTGRES_DB: ${POSTGRES_NAME}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_NAME}",
                ]
            interval: 10s
            timeout: 5s
            retries: 5
        # volumes:
        #     - ./postgres_data:/var/lib/postgresql/data
    api:
        container_name: api-container
        build:
            context: .
            dockerfile: docker/docker_files/Dockerfile
        restart: unless-stopped
        # restart: on-failure
        command: python manage.py runserver 0.0.0.0:8080
        # command: gunicorn backend.wsgi:application --bind 0.0.0.0:8080 --workers 3
        ports:
            - "8080:8080"
        volumes:
            - .:/app
        depends_on:
            db:
                condition: service_healthy
        environment:
            ADMIN_USER: ${ADMIN_USER}
            ADMIN_EMAIL: ${ADMIN_EMAIL}
            ADMIN_PASSWORD: ${ADMIN_PASSWORD}
